import hero from './hero'
import product from './product'
import process from './process'
import timeline from './timeline'
import faq from './faq'
import blog from './blog'
import content from './content'
import cta from './cta'
import about from './about'
import productPage from './productPage'
import patchTypes from './patchTypes'
import patchOption from './patchOption'
import industry from './industry'
import workSample from './workSample'
import ironOn from './ironOn'
import assetResource from './assetResource'
import craftsmanship from './craftsmanship'
import locationPage from './locationPage'
import patchStyle from './patchStyle'
import customProduct from './customProduct'
import sampleBox from './sampleBox'
import categoryPage from './categoryPage'

export const schemaTypes = [hero, product, process, timeline, faq, blog, content, cta, about, productPage, patchTypes, patchOption, industry, workSample, ironOn, assetResource, craftsmanship, locationPage, patchStyle, customProduct, sampleBox, categoryPage]